### PR TITLE
Fix null point exception when ssl_truststore_location is nil

### PR DESCRIPTION
**Pull request by kunna**
If `security_protocol` is set to "SASL_SSL" and `ssl_truststore_location` is blank. Null point exception happens.

I was trying to read data from Confluent Cloud and found this issue.

### CODE REVIEW

**Comment by colinsurprenant** [comment]
Thanks for your contribution @kunna. 

Could you please change your editor settings to keep trailing whitespaces and push a new commit to undo all these edits? Otherwise a 1 line change PR becomes a 22 lines changes and it becomes a mess with git blame etc. If you want to submit a cleanup PR after, it's fine but it should be separate from this specific bugfix.

Also, is `ssl_truststore_location` actually mandatory if you use SSL? I mean, will/can it work without a `ssl_truststore_location`? If not then we should trap that condition.

**Comment by colinsurprenant** [comment]
I don't think this is JSSE but rather for the Kafka client, see https://docs.confluent.io/3.2.0/kafka/ssl.html which seems to indicate it is mandatory. 
I am wondering if the right thing to do here is not to fail on empty/nil `ssl.truststore.location`?  OTOH if these are not valid the Kafka client will throw an exception and is certainly better than a NPE.

**Comment by kunna** [comment]
hum.. the document seems to indicate it is mandatory. but I have to leave it blank to access Confluent Cloud and they didn't give me any credentials. and example settings they provide does not include truststore.location. Confluent might be violating their own policy when serve Kafka as cloud service.

**Comment by colinsurprenant** [comment]
@kunna I don't see how this could be worst than the NPE we have now and this seems to be working for you: so just to confirm, your use-case is to leave `ssl_truststore_location` blank, did you manage to test to validate that your proposed modification actually works for you?

**Comment by kunna** [comment]
@colinsurprenant 
Yes, this modification works for me. I'm using it right now. This is the only way I can access to Confluent Cloud.

**Comment by colinsurprenant** [comment]
LGTM, will merge.
We need to followup with a version bump PR (bumping minor versions in gemspec and adding entry in the CHANGELOG). Let me know if you want to also submit that otherwise I can do it.

**Pull request merged**
