### PR TITLE
Added record timestamp to event decoration

### PR DESCRIPTION
**Pull request by consulthys**
This is a quick fix for #176 so event decorations contain the record timestamp.

### CODE REVIEW

**Comment by talevy** [comment]
thanks @consulthys, mind adding tests around this around here: https://github.com/logstash-plugins/logstash-input-kafka/blob/master/spec/integration/inputs/kafka_spec.rb#L91?

**Comment by consulthys** [comment]
Woops, of course ;-)

**Comment by consulthys** [comment]
Done. Also noticed that in the `.travis.yml` file, `KAFKA_VERSION` should be 0.10.1.1 instead of 0.10.1.0 in order to be consistent with the gem requirements.

**Comment by guyboertje** [comment]
@consulthys 
Apologies for the delay. Tal has moved to the ES Java side.
Please rebase this PR against master. I approve and will merge as soon as.

**Comment by consulthys** [comment]
Thanks @guyboertje I'll get back to this shortly

**Comment by consulthys** [comment]
There you go @guyboertje

**Comment by consulthys** [comment]
Fixed #176

**Pull request merged**
