### PR TITLE
bump to Kafka 0.10 client

### PR DESCRIPTION
**Pull request by talevy**

### CODE REVIEW

**Comment by suyograo** [comment]
Looks good. I will test with Kafka 0.10 tomorrow. Not sure why the tests fail!

**Comment by talevy** [comment]
broker didn't start up. might have made a typo or something. ran it locally

**Comment by suyograo** [comment]
@talevy can you rebase with https://github.com/logstash-plugins/logstash-input-kafka/pull/95 and then add new Kafka version to the matrix. This way we'll test both Kafka versions..

**Comment by suyograo** [comment]
@talevy ping to rebase

**Comment by suyograo** [comment]
LGTM

**Pull request merged**
