### PR TITLE
#218 fixed metadata_max_age_ms setting

### PR DESCRIPTION
**Pull request by original-brownbear**
The constant name just changed in Kafka and I adjusted it here.

### CODE REVIEW

**Comment by jsvd** [comment]
this is so strange, looking at http://supergsego.com/apache/kafka/0.10.0.1/javadoc/org/apache/kafka/clients/consumer/ConsumerConfig.html, it's the only setting with milisecond unit that doesn't have _MS_..

**Comment by original-brownbear** [comment]
@jsvd makes sense, in fact having a release with this is kinda important for an issue.

I'll add 2 PRs for 6.x and 7.x right?

**Comment by original-brownbear** [comment]
@jsvd ah I misread :) we'd have to create 6.x and 7.x to be able to do that in the first place, should I? :)

**Comment by jsvd** [comment]
I don't see a big issue with doing that, other than just extra (annoying) work, but I think it's better for the users

**Pull request closed without merging**
