### PR TITLE
Adds dual.commit.enabled and offsets.storage

### PR DESCRIPTION
**Pull request by gquintana**
- Depends on https://github.com/joekiller/jruby-kafka/pull/54
- http://fr.slideshare.net/jjkoshy/offset-management-in-kafka slide 34
- https://cwiki.apache.org/confluence/display/KAFKA/FAQ#FAQ-HowdowemigratetocommittingoffsetstoKafka(ratherthanZookeeper)in0.8.2

### CODE REVIEW

**Comment by karmi** [comment]
Hi @gquintana, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-input-kafka/pull/113.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by gquintana** [comment]
@karmi Done

**Comment by talevy** [comment]
@gquintana awesome! looks good. I notice that jruby-kafka may only be released in a few days (https://github.com/joekiller/jruby-kafka/issues/55). so I will wait on that for this to be merged!

Thanks for the contribution! this will make upgrading more bearable for sure

**Comment by joekiller** [comment]
@talevy @gquintana  sorry for the delay. jruby-kafka supposed the toggle with version 1.7.2 https://rubygems.org/gems/jruby-kafka/versions/1.7.2-java

**Comment by joekiller** [comment]
@gquintana I think updating https://github.com/gquintana/logstash-input-kafka/blob/v2.0.8.erdf/logstash-input-kafka.gemspec#L28 to 1.7.2 will fix it up.

**Comment by talevy** [comment]
sounds great. thanks @joekiller!

**Comment by lumost** [comment]
Hey All, 
Is this PR going to be merged in the future? It would be very useful to change logstash's offset storage.

**Comment by dominicbecker** [comment]
@gquintana Any plan to get this merged? Would be super useful for our use case.

**Comment by guyboertje** [comment]
@suyograo @talevy - do we still want this dual functionality?

**Comment by talevy** [comment]
@guyboertje sure, doesn't hurt. This is specifically intended for Kafka 0.8.2 consumers to commit to both kafka and zookeeper before completely upgrading to > 0.8 consumers.

**Pull request merged**
