### PR TITLE
Add compatability matrix to 2.x

### PR DESCRIPTION
**Pull request by dedemorton**

### CODE REVIEW

**Comment by prabhakar349** [comment]
@suyograo  where I can download the logstash 2.4 version which seems to be compatible with  kafka broker 0.10

**Comment by talevy** [comment]
Hi @prabhakar349. Although there will be an update to the plugins to enable support for Kafka 0.10 in Logstash 2.4. Logstash 2.4 has not yet been released, so there is no plugin compatible just yet, since there is no logstash 2.4 release just yet.

**Comment by prabhakar349** [comment]
@talevy I did tried to use logstash 2.3.4 , with the logstash-input-kafka version 2.0.9 with my current kafka 0.10.0.1 and seems its able to read messages from kafka. But after looking at the compatibility matrix I am worried whether I can use it or to find some other alternative to read messages from kafka before 2.4 is available

**Comment by talevy** [comment]
@prabhakar349 There are a few things going on. The compatibility is backwards between server -> client. That is to say, a kafka broker running on 0.10.x will continue to translate between kafka 0.8.x and 0.9.x protocols I believe. The other way around is not the case. Kafka 0.10 clients cannot communicate with 0.8 and 0.9 brokers.

**Pull request merged**
