### PR TITLE
breaking: Nest decorated fields under `@metadata`

### LINKED ISSUE #180: decorate_events content conflicts with metricbeat's kafka mapping
The decorate_event option in the kafka input adds pieces of information to the LS event like the following

```
  "kafka": {
    "consumer_group": "beats_indexers",
    "partition": 0,
```

However, this conflicts with [metricbeat's template](https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.template.json#L1732) where kafka.partition is an object, not a concrete value.

As a result, if you have something like metricbeats -> kafka -> LS (with decorate_events) -> ES (configured to use the metricbeats template), then all the events flowing through will fail with a mapping exception.

@talevy

### LINKED ISSUE #198: Move "decorate_events" fields into @metadata field
There is currently a conflict on the kafka.partitions field when using the Metricbeat Kafka module with the Logstash Kafka input decorate_events option. This event decoration is metadata, and should be put into the @metadata field where they can be extracted into a top-level field if desired. Addresses: https://github.com/logstash-plugins/logstash-input-kafka/issues/180

```
if @decorate_events
  event.set("[@metadata][kafka][topic]", record.topic)
  event.set("[@metadata][kafka][consumer_group]", @group_id)
  event.set("[@metadata][kafka][partition]", record.partition)
  event.set("[@metadata][kafka][offset]", record.offset)
  event.set("[@metadata][kafka][key]", record.key)
end
```

/cc @suyograo

### PR DESCRIPTION
**Pull request by suyograo**
Fixes #180

### CODE REVIEW

**Comment by original-brownbear** [comment]
LGTM :)

**Comment by jordansissel** [comment]
Might be a good time to document what metadata properties this plugin provides (I don't see any docs changes in this PR).

**Comment by suyograo** [comment]
@jordansissel +1. Added docs in https://github.com/logstash-plugins/logstash-input-kafka/pull/213/commits/cac9d596113e3621e64dfa55dcc704fd9af561f5

**Comment by acchen97** [comment]
@suyograo just so I understand, this change will only be applicable for Kafka 0.10.1.1? With our current plugin versioning here, it may be tricky to backport this to be compatible with older versions of Kafka even if we wanted to.

**Comment by suyograo** [comment]
@original-brownbear Correct. The Kafka version we are tracking now is `0.11` in master (or 7.x series). backporting this to older Kafka versions is just not worth the pain.

**Comment by suyograo** [comment]
oops, meant to @mention @acchen97 :)

**Comment by acchen97** [comment]
@suyograo ++ agreed.

/cc @ppf2 FYI this feature is only available in v7.0.0+ which is compatible with Kafka 0.11.

**Pull request merged**
