### PR TITLE
Update auto_commit_interval_ms to default to 5000

### LINKED ISSUE #90: auto_commit_interval_ms default should be the same as Kafka new consumer configuration default
As part of the validation work done in https://github.com/logstash-plugins/logstash-input-kafka/issues/88 

```
auto_commit_interval_ms -> 5000 (Note:  For this one, Kafka's new default is 5000, but ours is 10)
```

The auto_commit_interval_ms default for our Kafka input plugin is set to 10, but Kafka's new consumer default for this same parameter is 5000.

### PR DESCRIPTION
**Pull request by talevy**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

Fixes #90.

### CODE REVIEW

**Comment by suyograo** [comment]
LGTM. not sure why the build is failing. Kicked it off

**Comment by talevy** [comment]
strange. kicked it off again :) will take a deeper look if it fails again

**Comment by suyograo** [comment]
@talevy is this PR moot with #94 ?

**Comment by talevy** [comment]
well. depends if we want to update the 0.9 client or not

**Comment by suyograo** [comment]
Can we merge this to plugin-api-v1 then?

**Pull request merged**
