### PR TITLE
Adding SASL/Kerberos and bumping Kafka version

### PR DESCRIPTION
**Pull request by karanpradhan**

### CODE REVIEW

**Comment by talevy** [comment]
Hi @karanpradhan. thanks for the contribution! do you mind signing our CLA here: https://www.elastic.co/contributor-agreement/ ?

Also, since these changes are also compatible with 0.9, do you mind removing the version bump from this PR? and we can update support for the newer protocol in #94 

what do you think?

**Comment by karanpradhan** [comment]
@talevy The SASL/Kerberos config parameters have changed from kafka 0.9 as compared to kafka 0.10, so I think I might have to retain the version bump in this PR since it would not be backward compatible (for SASL protocol)

**Comment by talevy** [comment]
ah, I missed that. OK. do you think you could add tests using the travis test setup?

**Comment by karanpradhan** [comment]
@talevy I'm trying to test it locally, but kafka input in the config is not recognized. I have followed all the installation steps as well. I was using logstash 5.0.0 alpha3 . Is there anything else which I am missing.

**Comment by karanpradhan** [comment]
Testing would require a mock Kerberos server. I've tested locally but I think it would be kind of cumbersome to automate testing.

**Comment by suyograo** [comment]
@karanpradhan can you sign the CLA please?

**Comment by acchen97** [comment]
@karanpradhan thanks for this, its an important feature.

Can you please sign our [CLA](https://www.elastic.co/contributor-agreement)? Without it, we can't include your code here as a contributor.

**Comment by suyograo** [comment]
Closing due to inactivity. A new PR for Kerberos support is here: https://github.com/logstash-plugins/logstash-input-kafka/pull/150

**Pull request closed without merging**
