### PR TITLE
appropriately decorate event with the size of the message within Kafka.

### LINKED ISSUE #33: Decorating events assumes message field is a string
When `decorate_events` is set to `true`, `msg_size` is set by [calling `bytesize`](https://github.com/logstash-plugins/logstash-input-kafka/blob/112692fe61c731bce19d7fd355bbc4d28c30d7dd/lib/logstash/inputs/kafka.rb#L166) on the event's `message` field. This assumes that this field is always a string, and fails if it is a hash instead, as in my particular use-case.

### PR DESCRIPTION
**Pull request by talevy**
Assuming it is serialized differently than the message within Event,
this fix will be more representative of the true msgsize

Closes #33.

### CODE REVIEW

**Comment by joekiller** [comment]
Looks pretty good to me.  This'll include the whole package size: https://github.com/apache/kafka/blob/0.8.2/core/src/main/scala/kafka/message/Message.scala#L172 versus `payloadSize` which would be truly the "message" size.  Not sure which is desired. I think size is fine.

**Comment by suyograo** [comment]
I don't know many use cases of `msg_size` except for tracking Kafka overhead for messages, so I would prefer the entire package size as stored in Kafka. If there are other uses of this, we can change it

**Comment by talevy** [comment]
Cool. I'll keep it as is.

I will add some documentation to describe the contents of the decorated `kafka` field
to be more explicit.

**Comment by talevy** [comment]
updated

**Comment by talevy** [comment]
@joekiller what do you think?

**Comment by joekiller** [comment]
@talevy I likey.

**Pull request merged**
