### PR TITLE
add support for Kafka 0.10.1.0

### PR DESCRIPTION
**Pull request by talevy**
The biggest feature added to 0.10.1.0 is time-based offset searching [1]

Will investigate how to incorporate this into the plugin

[1] http://www.confluent.io/blog/announcing-apache-kafka-0-10-1-0/

### CODE REVIEW

**Comment by talevy** [comment]
this backwards compatibility test run shows that we might have to bump the version to `6.0`

https://travis-ci.org/logstash-plugins/logstash-input-kafka/builds/172205191

**Comment by talevy** [comment]
from their docs[1]:

```
Note: Because new protocols are introduced, it is important to upgrade your Kafka clusters before upgrading your clients (i.e. 0.10.1.x clients only support 0.10.1.x or later brokers while 0.10.1.x brokers also support older clients).
```

[1] https://kafka.apache.org/documentation#upgrade_10_1_breaking

**Comment by ppf2** [comment]
Thanks @talevy .  I don't see the new consumer setting `max_poll_interval_ms`  introduced in 0.10.1.0 in our [master](https://www.elastic.co/guide/en/logstash/master/plugins-inputs-kafka.html) doc yet.  Do we plan on adding it?  Maybe also note in its description that `request_timeout_ms` must always be larger than max_poll_interval_ms (which is a disclaimer in Kafka documentation)?

**Comment by talevy** [comment]
thanks @ppf2, the idea was to first enable speaking to `0.10.1.0` brokers and then following up with any enhancements like quering offsets by timestamp, and new configs.

will add those that you mention, for sure

**Comment by ppf2** [comment]
ok thx!

**Pull request merged**
