### PR TITLE
convert message_and_metadata.key to ruby string if its not nil

### PR DESCRIPTION
**Pull request by guyboertje**
Reviewers:
- This is to fix the accidental leaking of a org.jruby.java.proxies.ArrayJavaProxy into the Logstash Event.
- I can't test this with a real kafka key that is an array of bytes
- the existing test uses a Ruby class to simulate the Scala MessageAndMetadata class which obviously will not show the fault.

Consider creating a small Java class that implements the Decoder interface as a RubyStringDecoder that creates Ruby Strings directly from the bytes.

### CODE REVIEW

**Comment by talevy** [comment]
This can also be achieved by setting `key_decoder_class` to `kafka.serializer.StringDecoder`.

Since this is also the strategy of `message_and_metadata.message`, then I shall...

**Comment by talevy** [comment]
LGTM

**Comment by guyboertje** [comment]
@talevy - should we make that the default key and value decoder class = `kafka.serializer.StringDecoder` instead?

**Comment by talevy** [comment]
I consider changing defaults to be a breaking change. we would have to bump the version for that

**Comment by guyboertje** [comment]
Fair enough. In this particular case though, I would not be so strict.

**Comment by talevy** [comment]
true. it _probably_ would have been better to default to String from the beginning since it is being ruby-encoded as a string anyways.

**Comment by joekiller** [comment]
I implemented this in #79 fwiw.

**Comment by guyboertje** [comment]
@joekiller - Thanks man!

@talevy - I want to close this and help with getting #79 over the line?
The `key_decoder_class => "kafka.serializer.StringDecoder"` will act as a workaround until 79 is released.

**Comment by talevy** [comment]
@guyboertje that sounds reasonable to me. I am OK with closing this and moving the discussion to #79

**Pull request closed without merging**
