### PR TITLE
Update Kafka client to version 2.1.1

### PR DESCRIPTION
**Pull request by arenard**

### CODE REVIEW

**Comment by Erik-Securenative** [comment]
in kafka client 2.1.0 Client Not Following Broker IP Change and fixed on 2.1.1
We need this release

**Comment by jsvd** [comment]
[a new release has shipped with 2.3.0](https://github.com/logstash-plugins/logstash-input-kafka/commit/32b039ba87d746236075753490d1ab7b3b722b99), is that version ok or does it really need to be 2.1.1?

**Comment by Erik-Securenative** [comment]
Yes correct missed it its fixed the problem thanks

**Comment by jsvd** [comment]
thanks, closing here

**Pull request closed without merging**
